spring:
  application:
    name: "Homes-merry"

  datasource:
    url: "jdbc:mysql://localhost:3306/Homes_Merry"
    username: "root"
    password: "root@root"
    driver-class-name: "com.mysql.cj.jdbc.Driver"

  jpa:
    hibernate:
      ddl-auto: "update"
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: "org.hibernate.dialect.MySQLDialect"

debug: true